### ISSUE TITLE
Please post a sorted copy of the test file

### ISSUE THREAD

**Issue by DavidHaslam** [ninjaaron/ivsort.py#2]
Please post a sorted copy of the test file in order to compare the sort with various other methods.

**Comment by ninjaaron** [comment]
Sorted list is up!

**Comment by ninjaaron** [comment]
I realized that the trailing spaces because of the explanations were messing with the sort output ever so slightly (which is what it should do, in case there were a multi-word item to be sorted). It's not a major change, but something to keep in mind if you are going over the results with a magnifying glass, since the spaces do count before the vowels.
